### PR TITLE
Sniff for curio

### PR DESCRIPTION
**Pull request by smurfix**
(for now)

### CODE REVIEW

**Comment by njsmith** [comment]
I have mixed feelings about this. On the one hand, it's a practical workaround for Dave not wanting to support this. On the other hand, if Dave doesn't want to support sniffio's users, are we really doing them a favor by making it work despite him?

I'm not going to block it or anything, if sniffio's users want curio support then OK, just wanted to raise that consideration.

If we do go ahead with this then it should have a test.

**Comment by smurfix** [comment]
There's no test for trio either :-P but yes, adding explicit tests should be done, though I'll wait for Dave to decide one way or the other before doing even more work on what's a second-best solution IMHO.

**Comment by njsmith** [comment]
The trio support logic lives in trio, so that's where the tests are: https://github.com/python-trio/trio/blob/c6dcfddf53872cac3a769d62ebe056c106a1f220/trio/_core/tests/test_run.py#L1998

**Comment by smurfix** [comment]
I'd like to teach anyio to use this so that it interoperates with trio-asyncio, so I'd like to merge.

Test added.

**Comment by njsmith** [comment]
Cross-linking: The Curio PR is here: https://github.com/dabeaz/curio/pull/278

Dave rejected it because he thinks it should be in the stdlib. His strategy here doesn't make much sense to me – I know he wants to encourage the use of non-asyncio libraries, but that's never going to happen if we wait on the stdlib to lead the way!

I guess we might as well merge though.

@smurfix Why are we installing the dev version of curio instead of the released version? I'm going to try switching it and see if that works...

**Comment by njsmith** [comment]
That seems to have worked... I guess we're all distracted so instead of leaving this in case @smurfix has some important reason why we need to test against master, I'm going to go ahead and merge, and if there's some reason that's terrible then @smurfix can tell me afterwards :-)

**Comment by smurfix** [comment]
I initially tested against master because the last release on pypi is more than half a year old and I didn't want any "that bug has been fixed ages ago" problems. If it works against release, so much the better.

**Comment by njsmith** [comment]
Yeah, fortunately `curio.meta.curio_running` appears not to have changed at all recently.

My default in general is to test against the released version, on the theory that that's what people will use the library with, and because it insulates us against any day-to-day churn in unreleased branches. I guess I don't actually know whether curio users tend to use the released version or master, though...

**Pull request merged**
