### PR TITLE
Release 1.3.1

### PR DESCRIPTION
**Pull request by A5rocks**

### CODE REVIEW

**Comment by addyess** [comment]
with sniffio 1.3.1, i can no longer install into environments with very old setuptools

```
Processing ./wheelhouse/sniffio-1.3.1.tar.gz
Installing build dependencies: started
Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> [3 lines of output]
Looking in links: wheelhouse
ERROR: Could not find a version that satisfies the requirement setuptools>=64 (from versions: 62.1.0)
ERROR: No matching distribution found for setuptools>=64
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by A5rocks** [comment]
Do you know the oldest setuptools version that supports pep 517 off the top of your head? I can't find anything in the changelog but I saw some reference to fixing that in setup tools 40 at least.

**Comment by addyess** [comment]
@A5rocks, not sure.  I know my project was trying to use setuptools-62.1.0.  I was just reporting in case someone comes along with the same issue.  I'll pin to `sniffio==1.3.0` in this case

**Comment by A5rocks** [comment]
Looks like `setuptools==61.0.0` might be the first version that works for us (first version that does pep 621 style things). I'll check and if so, then I can drop the requirement and make a new release.

... On the other hand, I think a very simple solution for you if you wanted to use `sniffio==1.3.1` is to use something like `build` (`pip install build`) where you do something like `python -m build <path to sniffio> -w` then `pip install <built wheel path>` -- `build` makes an isolated venv and installs requirements into it, meaning no conflicts for building.

**Pull request merged**
