### PR TITLE
[WIP] Adjust for explicit support from Twisted

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
Twisted tests pass using corresponding preliminary PR.  Curio test failures to be addressed by #12. 
 Perhaps I cheated by changing the test to use an `async def`, or maybe that's more correct.  I'm not sure yet.

https://github.com/twisted/twisted/pull/1263

**Comment by njsmith** [comment]
If Twisted is going to start taking responsibility for setting the contextvar, then it might make sense to move the tests into Twisted. Following the principle that it's nice for the code being tested and the tests to live next to each other :-)

**Comment by altendky** [comment]
I guess sniffio just trusts in that case.  Will do.

**Comment by altendky** [comment]
For the record:
https://twistedmatrix.com/trac/ticket/9815
https://github.com/twisted/twisted/pull/1263

**Comment by altendky** [comment]
Dropping in favor of a clean PR.

**Pull request closed without merging**
